repeat wait(10) until game:IsLoaded()
loadstring(game:HttpGet("https://raw.githubusercontent.com/r6dt/farm/main/Del-CoreGui.lua"))()
task.wait(10)
loadstring(game:HttpGet("https://raw.githubusercontent.com/r6dt/farm/main/farm.lua"))()
task.wait(300)
loadstring(game:HttpGet("https://raw.githubusercontent.com/r6dt/farm/main/fps.lua"))()
